// File generated by FlutterFire CLI — replace with `flutterfire configure`.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Placeholder options so the app compiles before you run `flutterfire configure`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:0:web:replace',
    messagingSenderId: '0',
    projectId: 'demo-brijyatra-replace-me',
    authDomain: 'demo-brijyatra-replace-me.firebaseapp.com',
    storageBucket: 'demo-brijyatra-replace-me.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyReplaceMe9283746258473628',
    appId: '1:123456789012:android:abcdef0123456789abcd',
    messagingSenderId: '123456789012',
    projectId: 'demo-brijyatra-replace-me',
    storageBucket: 'demo-brijyatra-replace-me.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyReplaceMeIOS',
    appId: '1:123456789012:ios:abcdef0123456789abcd',
    messagingSenderId: '123456789012',
    projectId: 'demo-brijyatra-replace-me',
    storageBucket: 'demo-brijyatra-replace-me.appspot.com',
    iosBundleId: 'com.brijyatra.brijyatraMobile',
  );
}
