// File generated by FlutterFire CLI — replace with `flutterfire configure`.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Placeholder options so the app compiles before you run `flutterfire configure`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoQ4kkCJvfpbqFuY-j4lq5lYtzxfPbIU0',
    appId: '1:274212991371:web:08fbdee3757a3cbcd83f8e',
    messagingSenderId: '274212991371',
    projectId: 'brijyatra-8881f',
    authDomain: 'brijyatra-8881f.firebaseapp.com',
    storageBucket: 'brijyatra-8881f.firebasestorage.app',
    measurementId: 'G-KSYXKWT5VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDloTvzKwGFSsm0q0z99aJl1I-q0kSUbBM',
    appId: '1:274212991371:android:372d79c0f8a75b53d83f8e',
    messagingSenderId: '274212991371',
    projectId: 'brijyatra-8881f',
    storageBucket: 'brijyatra-8881f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeSSxs1TKcBpfJiFC_OR9BSYtkZw_U384',
    appId: '1:274212991371:ios:99daf4bb5ffa68bed83f8e',
    messagingSenderId: '274212991371',
    projectId: 'brijyatra-8881f',
    storageBucket: 'brijyatra-8881f.firebasestorage.app',
    iosBundleId: 'com.brijyatra.brijyatraMobile',
  );

}